language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t x35feng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true x35feng/docker-react npm run test

