language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t x35feng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true x35feng/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-469097562775"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
